export interface Venue {
  id: string
  name: string
  type: "bar" | "restaurant" | "parking"
  teamId: string
  distance: string
  walkingTime: string
  atmosphere: "tranquilo" | "animado" | "familiar" | "hinchada"
  capacity: number
  estimatedOccupancy: number
  rating: number
  reviewCount: number
  priceRange: "€" | "€€" | "€€€"
  reservationPrice: number
  address: string
  phone: string
  features: string[]
  matchDayHours: string
  position: { lat: number; lng: number }
  images: string[]
}

export const venues: Record<string, Venue[]> = {
  "fc-barcelona": [
    {
      id: "bar-camp-nou-1",
      name: "Bar La Penya Blaugrana",
      type: "bar",
      teamId: "fc-barcelona",
      distance: "150m",
      walkingTime: "2 min",
      atmosphere: "hinchada",
      capacity: 80,
      estimatedOccupancy: 75,
      rating: 4.6,
      reviewCount: 342,
      priceRange: "€€",
      reservationPrice: 5,
      address: "Carrer d'Arístides Maillol, 12",
      phone: "+34 93 411 2233",
      features: ["Pantallas gigantes", "Tapas catalanas", "Merchandising oficial"],
      matchDayHours: "10:00 - 00:00",
      position: { lat: 41.3819, lng: 2.1198 },
      images: [],
    },
    {
      id: "bar-camp-nou-2",
      name: "Can Culé",
      type: "bar",
      teamId: "fc-barcelona",
      distance: "200m",
      walkingTime: "3 min",
      atmosphere: "animado",
      capacity: 120,
      estimatedOccupancy: 60,
      rating: 4.4,
      reviewCount: 218,
      priceRange: "€€",
      reservationPrice: 5,
      address: "Travessera de les Corts, 88",
      phone: "+34 93 322 1144",
      features: ["Terraza", "Cervezas artesanas", "Bocadillos"],
      matchDayHours: "11:00 - 01:00",
      position: { lat: 41.3798, lng: 2.1245 },
      images: [],
    },
    {
      id: "restaurant-camp-nou-1",
      name: "El Racó del Camp Nou",
      type: "restaurant",
      teamId: "fc-barcelona",
      distance: "300m",
      walkingTime: "4 min",
      atmosphere: "familiar",
      capacity: 60,
      estimatedOccupancy: 45,
      rating: 4.7,
      reviewCount: 156,
      priceRange: "€€€",
      reservationPrice: 10,
      address: "Carrer de Joan XXIII, 15",
      phone: "+34 93 490 2211",
      features: ["Menú partido", "Cocina catalana", "Vinos DO"],
      matchDayHours: "12:00 - 16:00, 19:00 - 23:00",
      position: { lat: 41.3785, lng: 2.121 },
      images: [],
    },
    {
      id: "parking-camp-nou-1",
      name: "Parking Camp Nou Norte",
      type: "parking",
      teamId: "fc-barcelona",
      distance: "100m",
      walkingTime: "1 min",
      atmosphere: "tranquilo",
      capacity: 500,
      estimatedOccupancy: 85,
      rating: 4.2,
      reviewCount: 89,
      priceRange: "€€",
      reservationPrice: 15,
      address: "Acceso por Av. Joan XXIII",
      phone: "+34 93 496 3600",
      features: ["Vigilancia 24h", "Acceso rápido", "Carga eléctrica"],
      matchDayHours: "Abierto 3h antes - 2h después",
      position: { lat: 41.383, lng: 2.1228 },
      images: [],
    },
    {
      id: "parking-camp-nou-2",
      name: "Parking L'Illa Diagonal",
      type: "parking",
      teamId: "fc-barcelona",
      distance: "600m",
      walkingTime: "8 min",
      atmosphere: "tranquilo",
      capacity: 800,
      estimatedOccupancy: 40,
      rating: 4.5,
      reviewCount: 234,
      priceRange: "€€",
      reservationPrice: 12,
      address: "Av. Diagonal, 557",
      phone: "+34 93 444 0000",
      features: ["Centro comercial", "Menos saturación", "Cubierto"],
      matchDayHours: "08:00 - 02:00",
      position: { lat: 41.3867, lng: 2.1305 },
      images: [],
    },
  ],
  "real-madrid": [
    {
      id: "bar-bernabeu-1",
      name: "La Cervecería del Bernabéu",
      type: "bar",
      teamId: "real-madrid",
      distance: "100m",
      walkingTime: "1 min",
      atmosphere: "hinchada",
      capacity: 100,
      estimatedOccupancy: 90,
      rating: 4.5,
      reviewCount: 456,
      priceRange: "€€",
      reservationPrice: 5,
      address: "Paseo de la Castellana, 140",
      phone: "+34 91 344 5566",
      features: ["Historia del club", "Cerveza tirada", "Tapas madrileñas"],
      matchDayHours: "10:00 - 01:00",
      position: { lat: 40.4538, lng: -3.6883 },
      images: [],
    },
    {
      id: "bar-bernabeu-2",
      name: "Mesón Los Vikingos",
      type: "bar",
      teamId: "real-madrid",
      distance: "250m",
      walkingTime: "3 min",
      atmosphere: "animado",
      capacity: 150,
      estimatedOccupancy: 70,
      rating: 4.3,
      reviewCount: 289,
      priceRange: "€",
      reservationPrice: 5,
      address: "Calle del Padre Damián, 38",
      phone: "+34 91 457 2233",
      features: ["Gran terraza", "Precios populares", "Ambiente festivo"],
      matchDayHours: "11:00 - 02:00",
      position: { lat: 40.4515, lng: -3.691 },
      images: [],
    },
    {
      id: "restaurant-bernabeu-1",
      name: "Puerta 57",
      type: "restaurant",
      teamId: "real-madrid",
      distance: "50m",
      walkingTime: "1 min",
      atmosphere: "familiar",
      capacity: 80,
      estimatedOccupancy: 80,
      rating: 4.8,
      reviewCount: 512,
      priceRange: "€€€",
      reservationPrice: 15,
      address: "Estadio Santiago Bernabéu",
      phone: "+34 91 344 2020",
      features: ["Vistas al estadio", "Alta gastronomía", "Menú especial partido"],
      matchDayHours: "12:00 - 00:00",
      position: { lat: 40.453, lng: -3.6883 },
      images: [],
    },
    {
      id: "parking-bernabeu-1",
      name: "Parking Santiago Bernabéu",
      type: "parking",
      teamId: "real-madrid",
      distance: "0m",
      walkingTime: "0 min",
      atmosphere: "tranquilo",
      capacity: 600,
      estimatedOccupancy: 95,
      rating: 4.0,
      reviewCount: 178,
      priceRange: "€€€",
      reservationPrice: 25,
      address: "Estadio Santiago Bernabéu",
      phone: "+34 91 344 6000",
      features: ["Acceso directo", "Seguridad máxima", "Reserva obligatoria"],
      matchDayHours: "3h antes - 2h después",
      position: { lat: 40.453, lng: -3.689 },
      images: [],
    },
  ],
  "atletico-madrid": [
    {
      id: "bar-metropolitano-1",
      name: "Bar Atlético",
      type: "bar",
      teamId: "atletico-madrid",
      distance: "200m",
      walkingTime: "3 min",
      atmosphere: "hinchada",
      capacity: 90,
      estimatedOccupancy: 80,
      rating: 4.4,
      reviewCount: 267,
      priceRange: "€€",
      reservationPrice: 5,
      address: "Av. Luis Aragonés, 4",
      phone: "+34 91 566 2233",
      features: ["Ambiente colchonero", "Tapas", "Tertulia pre-partido"],
      matchDayHours: "10:00 - 00:00",
      position: { lat: 40.4372, lng: -3.5985 },
      images: [],
    },
    {
      id: "parking-metropolitano-1",
      name: "Parking Wanda",
      type: "parking",
      teamId: "atletico-madrid",
      distance: "100m",
      walkingTime: "2 min",
      atmosphere: "tranquilo",
      capacity: 400,
      estimatedOccupancy: 85,
      rating: 4.1,
      reviewCount: 145,
      priceRange: "€€",
      reservationPrice: 18,
      address: "Av. Luis Aragonés",
      phone: "+34 91 566 3600",
      features: ["Acceso rápido", "Vigilancia", "Plazas PMR"],
      matchDayHours: "3h antes - 2h después",
      position: { lat: 40.4368, lng: -3.598 },
      images: [],
    },
  ],
}

// Generate default venues for teams without specific data
const defaultVenueTypes = ["bar", "restaurant", "parking"] as const

export function getVenuesForTeam(teamId: string): Venue[] {
  if (venues[teamId]) {
    return venues[teamId]
  }

  // Generate default venues for teams without specific data
  return [
    {
      id: `bar-${teamId}-1`,
      name: "Bar del Estadio",
      type: "bar",
      teamId,
      distance: "150m",
      walkingTime: "2 min",
      atmosphere: "animado",
      capacity: 80,
      estimatedOccupancy: 65,
      rating: 4.3,
      reviewCount: 120,
      priceRange: "€€",
      reservationPrice: 5,
      address: "Junto al estadio",
      phone: "+34 900 000 000",
      features: ["Pantallas", "Tapas", "Ambiente partido"],
      matchDayHours: "10:00 - 00:00",
      position: { lat: 0, lng: 0 },
      images: [],
    },
    {
      id: `restaurant-${teamId}-1`,
      name: "Restaurante Local",
      type: "restaurant",
      teamId,
      distance: "300m",
      walkingTime: "4 min",
      atmosphere: "familiar",
      capacity: 50,
      estimatedOccupancy: 50,
      rating: 4.5,
      reviewCount: 85,
      priceRange: "€€",
      reservationPrice: 10,
      address: "Zona estadio",
      phone: "+34 900 000 001",
      features: ["Cocina local", "Menú partido", "Terraza"],
      matchDayHours: "12:00 - 23:00",
      position: { lat: 0, lng: 0 },
      images: [],
    },
    {
      id: `parking-${teamId}-1`,
      name: "Parking Estadio",
      type: "parking",
      teamId,
      distance: "100m",
      walkingTime: "1 min",
      atmosphere: "tranquilo",
      capacity: 300,
      estimatedOccupancy: 70,
      rating: 4.0,
      reviewCount: 60,
      priceRange: "€€",
      reservationPrice: 12,
      address: "Acceso principal",
      phone: "+34 900 000 002",
      features: ["Vigilancia", "Acceso rápido"],
      matchDayHours: "3h antes - 2h después",
      position: { lat: 0, lng: 0 },
      images: [],
    },
  ]
}
