import { type NextRequest, NextResponse } from "next/server"

// POI data - in production this would come from a database
const ALL_POIS = [
  // Barcelona POIs
  {
    id: "bcn-bar-1",
    name: "Bar La Penya Blaugrana",
    type: "bar",
    teamId: "barcelona",
    distance: "150m",
    walkingTime: "2 min",
    coordinates: { lat: 41.3809, lng: 2.1228 },
    address: "Carrer d'Arístides Maillol, 12",
    description: "Bar tradicional con ambiente blaugrana. Perfecto para calentar antes del partido.",
    features: ["Pantallas grandes", "Tapas", "Cerveza fría", "Wifi"],
    atmosphere: "hinchada",
    priceRange: "€€",
    openHours: "10:00 - 02:00",
    matchDayHours: "10:00 - 23:00",
    estimatedOccupancy: 65,
    rating: 4.6,
    reviewCount: 234,
    acceptsReservations: true,
    reservationPrice: 5,
  },
  {
    id: "bcn-bar-2",
    name: "Cervecería Camp Nou",
    type: "bar",
    teamId: "barcelona",
    distance: "200m",
    walkingTime: "3 min",
    coordinates: { lat: 41.3815, lng: 2.1235 },
    address: "Av. Joan XXIII, 45",
    description: "Amplio local con terraza ideal para grupos grandes.",
    features: ["Terraza", "Grupos", "Comida rápida", "Futbolín"],
    atmosphere: "animado",
    priceRange: "€€",
    openHours: "11:00 - 01:00",
    matchDayHours: "11:00 - 24:00",
    estimatedOccupancy: 45,
    rating: 4.3,
    reviewCount: 156,
    acceptsReservations: true,
    reservationPrice: 0,
  },
  {
    id: "bcn-rest-1",
    name: "Restaurante El Gol",
    type: "restaurant",
    teamId: "barcelona",
    distance: "300m",
    walkingTime: "4 min",
    coordinates: { lat: 41.3795, lng: 2.121 },
    address: "Carrer de Numància, 88",
    description: "Cocina catalana con vistas al estadio. Menú especial día de partido.",
    features: ["Cocina catalana", "Vistas estadio", "Menú partido", "Reservas online"],
    atmosphere: "familiar",
    priceRange: "€€€",
    openHours: "12:00 - 23:30",
    matchDayHours: "12:00 - 21:00",
    estimatedOccupancy: 70,
    rating: 4.5,
    reviewCount: 312,
    acceptsReservations: true,
    reservationPrice: 10,
  },
  {
    id: "bcn-park-1",
    name: "Parking Nord Camp Nou",
    type: "parking",
    teamId: "barcelona",
    distance: "100m",
    walkingTime: "1 min",
    coordinates: { lat: 41.3825, lng: 2.123 },
    address: "Acceso Norte Camp Nou",
    description: "Parking oficial con acceso directo al estadio.",
    features: ["Vigilado 24h", "Acceso directo", "Reserva online", "Carga eléctrica"],
    atmosphere: "tranquilo",
    priceRange: "€€€",
    openHours: "24 horas",
    matchDayHours: "Abre 4h antes del partido",
    estimatedOccupancy: 85,
    rating: 4.2,
    reviewCount: 89,
    acceptsReservations: true,
    reservationPrice: 25,
  },
  {
    id: "bcn-trans-1",
    name: "Metro Les Corts (L3)",
    type: "transport",
    teamId: "barcelona",
    distance: "350m",
    walkingTime: "5 min",
    coordinates: { lat: 41.3775, lng: 2.118 },
    address: "Estación Les Corts, L3",
    description: "Línea verde directa al centro. Frecuencia aumentada días de partido.",
    features: ["L3 Verde", "Alta frecuencia", "Accesible"],
    atmosphere: "tranquilo",
    priceRange: "€",
    openHours: "05:00 - 24:00",
    matchDayHours: "Servicio extendido",
    estimatedOccupancy: 75,
    rating: 4.4,
    reviewCount: 445,
    acceptsReservations: false,
    reservationPrice: 0,
  },
  // Real Madrid POIs
  {
    id: "rm-bar-1",
    name: "La Casa Blanca Sports Bar",
    type: "bar",
    teamId: "real-madrid",
    distance: "120m",
    walkingTime: "2 min",
    coordinates: { lat: 40.4531, lng: -3.6883 },
    address: "Paseo de la Castellana, 142",
    description: "El bar madridista por excelencia. Historia y tradición blanca.",
    features: ["Memorabilia RM", "Cañas perfectas", "Historia", "Ambiente único"],
    atmosphere: "hinchada",
    priceRange: "€€",
    openHours: "10:00 - 02:00",
    matchDayHours: "10:00 - 24:00",
    estimatedOccupancy: 80,
    rating: 4.7,
    reviewCount: 567,
    acceptsReservations: true,
    reservationPrice: 5,
  },
  {
    id: "rm-park-1",
    name: "Parking Santiago Bernabéu",
    type: "parking",
    teamId: "real-madrid",
    distance: "0m",
    walkingTime: "0 min",
    coordinates: { lat: 40.453, lng: -3.688 },
    address: "Subterráneo del estadio",
    description: "Parking oficial bajo el estadio. Acceso VIP disponible.",
    features: ["Oficial", "Subterráneo", "Carga eléctrica", "Seguridad 24h"],
    atmosphere: "tranquilo",
    priceRange: "€€€€",
    openHours: "24 horas",
    matchDayHours: "Reserva obligatoria",
    estimatedOccupancy: 95,
    rating: 4.3,
    reviewCount: 156,
    acceptsReservations: true,
    reservationPrice: 35,
  },
  {
    id: "rm-trans-1",
    name: "Metro Santiago Bernabéu (L10)",
    type: "transport",
    teamId: "real-madrid",
    distance: "100m",
    walkingTime: "1 min",
    coordinates: { lat: 40.4525, lng: -3.689 },
    address: "Estación Santiago Bernabéu, L10",
    description: "Acceso directo al estadio. La opción más cómoda.",
    features: ["L10", "Acceso directo", "Frecuencia alta"],
    atmosphere: "tranquilo",
    priceRange: "€",
    openHours: "06:00 - 01:30",
    matchDayHours: "Servicio extendido hasta 02:30",
    estimatedOccupancy: 85,
    rating: 4.5,
    reviewCount: 678,
    acceptsReservations: false,
    reservationPrice: 0,
  },
  // Atlético Madrid POIs
  {
    id: "atm-bar-1",
    name: "Bar Rojiblanco",
    type: "bar",
    teamId: "atletico-madrid",
    distance: "200m",
    walkingTime: "3 min",
    coordinates: { lat: 40.4363, lng: -3.5995 },
    address: "Av. Luis Aragonés, 15",
    description: "El corazón colchonero. Ambiente auténtico de hinchada.",
    features: ["Auténtico", "Bufandas", "Cánticos", "Cerveza fría"],
    atmosphere: "hinchada",
    priceRange: "€€",
    openHours: "10:00 - 02:00",
    matchDayHours: "10:00 - 24:00",
    estimatedOccupancy: 70,
    rating: 4.5,
    reviewCount: 345,
    acceptsReservations: true,
    reservationPrice: 5,
  },
  {
    id: "atm-park-1",
    name: "Parking Wanda",
    type: "parking",
    teamId: "atletico-madrid",
    distance: "150m",
    walkingTime: "2 min",
    coordinates: { lat: 40.437, lng: -3.5998 },
    address: "Acceso Parking Metropolitano",
    description: "Gran capacidad y buena salida post-partido.",
    features: ["Gran capacidad", "Vigilado", "Fácil acceso"],
    atmosphere: "tranquilo",
    priceRange: "€€€",
    openHours: "24 horas",
    matchDayHours: "Abre 4h antes",
    estimatedOccupancy: 75,
    rating: 4.1,
    reviewCount: 123,
    acceptsReservations: true,
    reservationPrice: 20,
  },
]

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url)
  const teamId = searchParams.get("teamId")
  const type = searchParams.get("type")

  let filteredPois = ALL_POIS

  if (teamId) {
    filteredPois = filteredPois.filter((poi) => poi.teamId === teamId)
  }

  if (type) {
    filteredPois = filteredPois.filter((poi) => poi.type === type)
  }

  // Simulate real-time occupancy updates
  const poisWithLiveData = filteredPois.map((poi) => ({
    ...poi,
    estimatedOccupancy: Math.min(100, poi.estimatedOccupancy + Math.floor(Math.random() * 10) - 5),
  }))

  return NextResponse.json({ pois: poisWithLiveData })
}
